package com.example.schedule;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

import com.example.constitutionofindia.R;

public class Schedule06 extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_schedule06);

        setTitle("Schedule 06");

        TextView textView = findViewById(R.id.content);

        textView.setText("SIXTH SCHEDULE\n" +
                "[Articles 244(2) and 275(1)]\n" +
                "Provisions as to the Administration of Tribal Areas in the States of Assam, Meghalaya, Tripura and Mizoram\n" +
                "1. Autonomous districts and autonomous regions.(1) Subject to the provisions of this paragraph, the tribal areas in each item of Parts I, II and IIA and in Part III of the table appended to paragraph 20 of this Schedule shall be an autonomous district. (Paragraph 1 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, so as to insert the following proviso after sub-paragraph (2), namely:\n" +
                "Provided that nothing in this sub-paragraph shall apply to the Bodoland Territorial Areas District.\"\n" +
                "(2) If there are different Scheduled Tribes in an autonomous district, the Governor may, by public notification, divide the area or areas inhabited by them into autonomous regions.\n" +
                "(3) The Governor may, by public notification,\n" +
                "(a) include any area in any of the Parts of the said table,\n" +
                "(b) exclude any area from any of the Parts of the said table,\n" +
                "(c) create a new autonomous district,\n" +
                "(d) increase the area of any autonomous district,\n" +
                "(e) diminish the area of any autonomous district,\n" +
                "(f) unite two or more autonomous districts or parts thereof so as to form one autonomous district,\n" +
                "(ff) alter the name of any autonomous district,\n" +
                "(g) define the boundaries of any autonomous district:\n" +
                "Provided that no order shall be made by the Governor under clauses (c), (d), (e) and (f) of this sub-paragraph except after consideration of the report of a Commission appointed under sub-paragraph (1) of paragraph 14 of this Schedule: \n" +
                "Provided further that any order made by the Governor under this sub-paragraph may contain such incidental and consequential provisions (including any amendment of paragraph 20 and of any item in any of the Parts of the said Table) as appear to the Governor to be necessary for giving effect to the provisions of the order.\n" +
                "2. Constitution of District Councils and Regional Councils.\n" +
                "(1) There shall be a District Council for each autonomous district consisting of not more than thirty members, of whom not more than four persons shall be nominated by the Governor and the rest shall be elected on the basis of adult suffrage.\n" +
                "*Paragraph 2 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, so as to insert the following proviso after sub-paragraph (1), namely: \n" +
                "Provided that the Bodoland Territorial Council shall consist of not more than forty-six members of whom forty shall be elected on the basis of adult suffrage, of whom thirty shall be reserved for the Scheduled Tribes, five for non-tribal communities, five open for all communities and the remaining six shall be nominated by the Governor having same rights and privileges as other members, including voting rights, from amongst the un-represented communities of the Bodoland Territorial Areas District, of which at least two shall be women :\n" +
                "** Paragraph 2 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 1995 (42 of 1995), s.2, so as to insert the following proviso after sub-paragraph (3), namely : \n" +
                "Provided that the District Council constituted for the North Cachar Hills District shall be called as the North Cachar Hills Autonomous Council and the District Council constituted for the Karbi Anglong District shall be called as the Karbi Anglong Autonomous Council.\n" +
                "* Paragraph 2 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, so as to insert the following proviso after sub-paragraph (3), namely: \n" +
                "Provided further that the District Council constituted for the Bodoland Territorial Areas District shall be called the Bodoland Territorial Council.\n" +
                "(2) There shall be a separate Regional Council for each area constituted an autonomous region under sub-paragraph (2) of paragraph 1 of this Schedule.\n" +
                "(3) Each District Council and each Regional Council shall be a body corporate by the name respectively of the District Council of (name of district) and the Regional Council of (name of region), shall have perpetual succession and a common seal and shall by the said name sue and be sued.\n" +
                "(4) Subject to the provisions of this Schedule, the administration of an autonomous district shall, in so far as it is not vested under this Schedule in any Regional Council within such district, be vested in the District Council for such district and the administration of an autonomous region shall be vested in the Regional Council for such region.\n" +
                "(5) In an autonomous district with Regional Councils, the District Council shall have only such powers with respect to the areas under the authority of the Regional Council as may be delegated to it by the Regional Council in addition to the powers conferred on it by this Schedule with respect to such areas.\n" +
                "(6) The Governor shall make rules for the first constitution of District Councils and Regional Councils in consultation with the existing tribal Councils or other representative tribal organisations within the autonomous districts or regions concerned, and such rules shall provide for\n" +
                "(a) the composition of the District Councils and Regional Councils and the allocation of seats therein;\n" +
                "(b) the delimitation of territorial constituencies for the purpose of elections to those Councils;\n" +
                "(c) the qualifications for voting at such elections and the preparation of electoral rolls therefor;\n" +
                "(d) the qualifications for being elected at such elections as members of such Councils;\n" +
                "(e) the term of office of members of Regional Councils;\n" +
                "(f) any other matter relating to or connected with elections or nominations to such Councils;\n" +
                "(g) the procedure and the conduct of business (including the power to act notwithstanding any vacancy) in the District and Regional Councils;\n" +
                "(h) the appointment of officers and staff of the District and Regional Councils.\n" +
                "(6A) The elected members of the District Council shall hold office for a term of five years from the date appointed for the first meeting of the Council after the general elections to the Council, unless the District Council is sooner dissolved under paragraph 16 and a nominated member shall hold office at the pleasure of the Governor:\n" +
                "Provided that the said period of five years may, while a Proclamation of Emergency is in operation or if circumstances exist which, in the opinion of the Governor, render the holding of elections impracticable, be extended by the Governor for a period not exceeding one year at a time and in any case where a Proclamation of Emergency is in operation not extending beyond a period of six months after the Proclamation has ceased to operate:\n" +
                "Provided further that a member elected to fill a casual vacancy shall hold office only for the remainder of the term of office of the member whom he replaces.\n" +
                "(7) The District or the Regional Council may after its first constitution make rules with the approval of the Governor with regard to the matters specified in sub-paragraph (6) of this paragraph and may also make rules with like approval regulating\n" +
                "(a) the formation of subordinate local Councils or Boards and their procedure and the conduct of their business; and\n" +
                "(b) generally all matters relating to the transaction of business pertaining to the administration of the district or region, as the case may be:\n" +
                "Provided that until rules are made by the District or the Regional Council under this sub-paragraph the rules made by the Governor under sub-paragraph\n" +
                "(6) of this paragraph shall have effect in respect of elections to, the officers and staff of, and the procedure and the conduct of business in, each such Council.\n" +
                "Provided further that a member elected to fill a casual vacancy shall hold office only for the remainder of the term of office of the member whom he replaces.\n" +
                "(7) The District or the Regional Council may after its first constitution make rules with the approval of the Governor with regard to the matters specified in sub-paragraph (6) of this paragraph and may also make rules with like approval regulating\n" +
                "(a) the formation of subordinate local Councils or Boards and their procedure and the conduct of their business; and\n" +
                "(b) generally all matters relating to the transaction of business pertaining to the administration of the district or region, as the case may be:\n" +
                "Provided that until rules are made by the District or the Regional Council under this sub-paragraph the rules made by the Governor under sub-paragraph\n" +
                "(6) of this paragraph shall have effect in respect of elections to, the officers and staff of, and the procedure and the conduct of business in, each such Council.\n" +
                "3. Powers of the District Councils and Regional Councils to make laws.(1) The Regional Council for an autonomous region in respect of all areas within such region and the District Council for an autonomous district in respect of all areas within the district except those which are under the authority of Regional Councils, if any, within the district shall have power to make laws with respect to\n" +
                "(a) the allotment, occupation or use, or the setting apart, of land, other than any land which is a reserved forest for the purposes of agriculture or grazing or for residential or other non-agricultural purposes or for any other purpose likely to promote the interests of the inhabitants of any village or town: \n" +
                "Provided that nothing in such laws shall prevent the compulsory acquisition of any land, whether occupied or unoccupied, for public purposes by the Government of the State concerned in accordance with the law for the time being in force authorising such acquisition;\n" +
                "(b) the management of any forest not being a reserved forest;\n" +
                "(c) the use of any canal or water-course for the purpose of agriculture;\n" +
                "(d) the regulation of the practice of jhum or other forms of shifting cultivation;\n" +
                "(e) the establishment of village or town committees or councils and their powers;\n" +
                "(f) any other matter relating to village or town administration, including village or town police and public health and sanitation;\n" +
                "(g) the appointment or succession of Chiefs or Headmen;\n" +
                "(h) the inheritance of property;\n" +
                "(i) marriage and divorce;\n" +
                "(j) social customs.\n" +
                "(2) In this paragraph, a reserved forest means any area which is a reserved forest under the Assam Forest Regulation, 1891, or under any other law for the time being in force in the area in question.\n" +
                "(3) All laws made under this paragraph shall be submitted forthwith to the Governor and, until assented to by him, shall have no effect.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 3 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2 , so as to substitute sub-paragraph (3) as under, - \n" +
                "(3) Save as otherwise provided in sub-paragraph (2) of paragraph 3A or sub-paragraph (2) of paragraph 3B, all laws made under this paragraph or sub-paragraph (1) of paragraph 3A or sub-paragraph (1) of paragraph 3B shall be submitted forthwith to the Governor and, until assented to by him, shall have no effect.\n" +
                "note[2] After paragraph 3, the following paragraph has been inserted in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 1995 (42 of 1995), s. 2 and after paragraph 3A, the following paragraph has been inserted in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, namely: \n" +
                "3A. Additional powers of the North Cachar Hills Autonomous Council and the Karbi Anglong Autonomous Council to make laws.(1) Without prejudice to the provisions of paragraph 3, the North Cachar Hills Autonomous Council and the Karbi Anglong Autonomous Council within their respective districts, shall have power to make laws with respect to\n" +
                "(a) industries, subject to the provisions of entries 7 and 52 of List I of the Seventh Schedule;\n" +
                "(b) communications, that is to say, roads, bridges, ferries and other means of communication not specified in List I of the Seventh Schedule; municipal tramways, ropeways, inland waterways and traffic thereon subject to the provisions of List I and List III of the Seventh Schedule with regard to such waterways; vehicles other than mechanically propelled vehicles;\n" +
                "(c) preservation, protection and improvement of stock and prevention of animal diseases; veterinary training and practice; cattle pounds;\n" +
                "(d) primary and secondary education;\n" +
                "(e) agriculture, including agricultural education and research, protection against pests and prevention of plant diseases;\n" +
                "(f) fisheries;\n" +
                "(g) water, that is to say, water supplies, irrigation and canals, drainage and embankments, water storage and water power subject to the provisions of entry 56 of List I of the Seventh Schedule;\n" +
                "(h) social security and social insurance; employment and unemployment;\n" +
                "(i) flood control schemes for protection of villages, paddy fields, markets, towns, etc. (not of technical nature);\n" +
                "(j) theatre and dramatic performances, cinemas subject to the provisions of entry 60 of List I of the Seventh Schedule; sports, entertainments and amusements;\n" +
                "(k) public health and sanitation, hospitals and dispensaries;\n" +
                "(l) minor irrigation;\n" +
                "(m) trade and commerce in, and the production supply and distribution of, food stuffs, cattle fodder, raw cotton and raw jute;\n" +
                "(n) libraries, museums and other similar institutions controlled or financed by the State; ancient and historical monuments and records other than those declared by or under any law made by Parliament to be of national importance; and\n" +
                "(o) alienation of land.\n" +
                "(2) All laws made by the North Cachar Hills Autonomous Council and the Karbi Anglong Autonomous Council under paragraph 3 or under this paragraph shall, in so far as they relate to matters specified in List III of the Seventh Schedule, be submitted forthwith to the Governor who shall reserve the same for the consideration of the President.\n" +
                "(3) When a law is reserved for the consideration of the President, the President shall declare either that he assents to the said law or that he withholds assent therefrom: \n" +
                "Provided that the President may direct the Governor to return the law to the North Cachar Hills Autonomous Council or the Karbi Anglong Autonomous Council, as the case may be, together with a message requesting that the said Council will reconsider the law or any specified provisions thereof and, in particular, will consider the desirability of introducing any such amendments as he may recommend in his message and, when the law is so returned, the said Council shall consider the law accordingly within a period of six months from the date of receipt of such message and, if the law is again passed by the said Council with or without amendment it shall be presented again to the President for his consideration.\"\n" +
                "note[3] After paragraph 3A, the following paragraph has been inserted in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, namely:--\n" +
                "3B. Additional powers of the Bodoland Territorial Council to make laws.(1) Without prejudice to the provisions of paragraph 3, the Bodoland Territorial Council within its areas shall have power to make laws with respect to :-\n" +
                "(i) agriculture, including agricultural education and research, protection against pests and prevention of plant diseases;\n" +
                "(ii) animal husbandry and veterinary, that is to say, preservation, protection and improvement of stock and prevention of animal diseases, veterinary training and practice, cattle pounds;\n" +
                "(iii) co-operation;\n" +
                "(iv) cultural affairs;\n" +
                "(v) education, that is to say, primary education, higher secondary including vocational training, adult education, college education (general);\n" +
                "(vi) fisheries;\n" +
                "(vii) flood control for protection of village, paddy fields, markets and towns (not of technical nature);\n" +
                "(viii) Food and civil supply;\n" +
                "(ix) forests (other than reserved forests);\n" +
                "(x) handloom and textile;\n" +
                "(xi) health and family welfare,\n" +
                "(xii) intoxicating liquors, opium and derivatives, subject to the provisions of entry 84 of List I of the Seventh Schedule;\n" +
                "(xiii) irrigation;\n" +
                "(xiv) labour and employment;\n" +
                "(xv) land and revenue;\n" +
                "(xvi) library services (financed and controlled by the State Government);\n" +
                "(xvii) lotteries (subject to the provisions of entry 40 of List I of the Seventh Schedule), theatres, dramatic performances and cinemas (subject to the provisions of entry 60 of List I of the Seventh Schedule);\n" +
                "(xviii) markets and fairs;\n" +
                "(xix) municipal corporation, improvement trust, district boards and other local authorities;\n" +
                "(xx) museum and archaeology institutions controlled or financed by the State, ancient and historical monuments and records other than those declared by or under any law made by Parliament to be of national importance;\n" +
                "(xxi) panchayat and rural development;\n" +
                "(xxii) planning and development;\n" +
                "(xxiii) printing and stationery;\n" +
                "(xxiv) pubic health engineering;\n" +
                "(xxv) public works department;\n" +
                "(xxvi) publicity and public relations;\n" +
                "(xxvii) registration of births and deaths;\n" +
                "(xxviii) relief and rehabilitation;\n" +
                "(xxix) sericulture;\n" +
                "(xxx) small, cottage and rural industry subject to the provisions of entries 7 and 52 of List I of the Seventh Schedule;\n" +
                "(xxxi) social Welfare;\n" +
                "(xxxii) soil conservation;\n" +
                "(xxxiii) sports and youth welfare;\n" +
                "(xxxiv) statistics;\n" +
                "(xxxv) tourism;\n" +
                "(xxxvi) transport (roads, bridges, ferries and other means of communications not specified in List I of the Seventh Schedule, municipal tramways, ropeways, inland waterways and traffic thereon subject to the provision of List I and List III of the Seventh Schedule with regard to such waterways, vehicles other than mechanically propelled vehicles);\n" +
                "(xxxvii) tribal research institute controlled and financed by the State Government;\n" +
                "(xxxviii) urban developmenttown and country planning;\n" +
                "(xxxix) weights and measures subject to the provisions of entry 50 of List I of the Seventh Schedule; and\n" +
                "(xl) Welfare of plain tribes and backward classes:\n" +
                "\n" +
                "Provided that nothing in such laws shall\n" +
                "(a) extinguish or modify the existing rights and privileges of any citizen in respect of his land at the date of commencement of this Act; and\n" +
                "(b) disallow and citizen from acquiring land either by way of inheritance, allotment, settlement or by any other way of transfer if such citizen is otherwise eligible for such acquisition of land within the Bodoland Territorial Areas District.\n" +
                "(2) All laws made under paragraph 3 or under this paragraph shall in so far as they relate to matters specified in List III of the Seventh Schedule, be submitted forthwith to the Governor who shall reserve the same for the consideration of the President.\n" +
                "(3) When a law is reserved for the consideration of the President, the President shall declare either that he assents to the said law or that he withholds assent therefrom:\n" +
                "Provided that the President may direct the Governor to return the law to the Bodoland Territorial Council, together with the message requesting that the said Council will reconsider the law or any specified provisions thereof and, in particular, will consider the desirability of introducing any such amendments as he may recommend in his message and, when the law is so returned, the said Council shall consider the law accordingly within a period of six month from the date of receipt of such message and, if the law is again passed by the said Council with or without amendments it shall be presented again to the President for his consideration.\n" +
                "-----------------------\n" +
                "4. Administration of justice in autonomous districts and autonomous regions.(1) The Regional Council for an autonomous region in respect of areas within such region and the District Council for an autonomous district in respect of areas within the district other than those which are under the authority of the Regional Councils, if any, within the district may constitute village councils or courts for the trial of suits and cases between the parties all of whom belong to Scheduled Tribes within such areas, other than suits and cases to which the provisions of sub-paragraph (1) of paragraph 5 of this Schedule apply, to the exclusion of any court in the State, and may appoint suitable persons to be members of such village councils or presiding officers of such courts, and may also appoint such officers as may be necessary for the administration of the laws made under paragraph 3 of this Schedule. \n" +
                "-----------------------\n" +
                "note[1] Paragraph 4 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, so as to insert the following sub-paragraph after sub-paragraph (5), namely :\n" +
                "(6) Nothing in this paragraph shall apply to the Bodoland Territorial Council constituted under the proviso to sub-paragraph (3) of paragraph 2 of this Schedule.\n" +
                "-----------------------\n" +
                "(2) Notwithstanding anything in this Constitution, the Regional Council for an autonomous region or any court constituted in that behalf by the Regional Council or, if in respect of any area within an autonomous district there is no Regional Council, the District Council for such district, or any court constituted in that behalf by the District Council, shall exercise the powers of a court of appeal in respect of all suits and cases triable by a village council or court constituted under sub-paragraph (1) of this paragraph within such region or area, as the case may be, other than those to which the provisions of sub-paragraph (1) of paragraph 5 of this Schedule apply, and no other court except the High Court and the Supreme Court shall have jurisdiction over such suits or cases.\n" +
                "(3) The High Court shall have and exercise such jurisdiction over the suits and cases to which the provisions of sub-paragraph (2) of this paragraph apply as the Governor may from time to time by order specify.\n" +
                "(4) A Regional Council or District Council, as the case may be, may with the previous approval of the Governor make rules regulating \n" +
                "(a) the constitution of village councils and courts and the powers to be exercised by them under this paragraph;\n" +
                "(b) the procedure to be followed by village councils or courts in the trial of suits and cases under sub-paragraph (1) of this paragraph;\n" +
                "(c) the procedure to be followed by the Regional or District Council or any court constituted by such Council in appeals and other proceedings under sub-paragraph (2) of this paragraph;\n" +
                "(d) the enforcement of decisions and orders of such councils and courts;\n" +
                "(e) all other ancillary matters for the carrying out of the provisions of sub-paragraphs (1) and (2) of this paragraph.\n" +
                "(5) On and from such date as the President may, after consulting the Government of the State concerned, by notification appoint in this behalf, this paragraph shall have effect in relation to such autonomous district or region as may be specified in the notification, as if\n" +
                "(i) in sub-paragraph (1), for the words between the parties all of whom belong to Scheduled Tribes within such areas, other than suits and cases to which the provisions of sub-paragraph (1) of paragraph 5 of this Schedule apply,, the words not being suits and cases of the nature referred to in sub-paragraph (1) of paragraph (5) of this Schedule, which the Governor may specify in this behalf, had been substituted;\n" +
                "(ii) sub-paragraphs (2) and (3) had been omitted;\n" +
                "(iii) in sub-paragraph (4) \n" +
                "(a) for the words A Regional Council or District Council, as the case may be, may with the previous approval of the Governor make rules regulating, the words the Governor may make rules regulating had been substituted; and\n" +
                "(b) for clause (a), the following clause had been substituted, namely:\n" +
                "(a) the constitution of village councils and courts, the powers to be exercised by them under this paragraph and the courts to which appeals from the decisions of village councils and courts shall lie;;\n" +
                "(c) for clause (c), the following clause had been substituted, namely:\n" +
                "(c) the transfer of appeals and other proceedings pending before the Regional or District Council or any court constituted by such Council immediately before the date appointed by the President under sub-paragraph (5);; and\n" +
                "(d) in clause (e), for the words, brackets and figures sub-paragraphs (1) and (2), the word, brackets and figure sub-paragraph (1) had been substituted. \n" +
                "5. Conferment of powers under the Code of Civil Procedure, 1908, and the Code of Criminal Procedure, 1898 (See now the Code of Criminal Procedure, 1973 (Act 2 of 1974)), on the Regional and District Councils and on certain courts and officers for the trial of certain suits, cases and offences.(1) The Governor may, for the trial of suits or cases arising out of any law in force in any autonomous district or region being a law specified in that behalf by the Governor, or for the trial of offences punishable with death, transportation for life, or imprisonment for a term of not less than five years under the Indian Penal Code or under any other law for the time being applicable to such district or region, confer on the District Council or the Regional Council having authority over such district or region or on courts constituted by such District Council or on any officer appointed in that behalf by the Governor, such powers under the Code of Civil Procedure, 1908, or, as the case may be, the Code of Criminal Procedure, 18981, as he deems appropriate, and thereupon the said Council, court or officer shall try the suits, cases or offences in exercise of the powers so conferred.\n" +
                "(2) The Governor may withdraw or modify any of the powers conferred on a District Council, Regional Council, court or officer under sub-paragraph (1) of this paragraph.\n" +
                "(3) Save as expressly provided in this paragraph, the Code of Civil Procedure, 1908, and the Code of Criminal Procedure, 18981, shall not apply to the trial of any suits, cases or offences in an autonomous district or in any autonomous region to which the provisions of this paragraph apply.\n" +
                "(4) On and from the date appointed by the President under sub-paragraph (5) of paragraph 4 in relation to any autonomous district or autonomous region, nothing contained in this paragraph shall, in its application to that district or region, be deemed to authorise the Governor to confer on the District Council or Regional Council or on courts constituted by the District Council any of the powers referred to in sub-paragraph (1) of this paragraph.\n" +
                "6. Powers of the District Council to establish primary schools, etc.\n" +
                "(1) The District Council for an autonomous district may establish, construct, or manage primary schools, dispensaries, markets, cattle pounds, ferries, fisheries, roads, road transport and waterways in the district and may, with the previous approval of the Governor, make regulations for the regulation and control thereof and, in particular, may prescribe the language and the manner in which primary education shall be imparted in the primary schools in the district. \n" +
                "(2) The Governor may, with the consent of any District Council, entrust either conditionally or unconditionally to that Council or to its officers functions in relation to agriculture, animal husbandry, community projects, co-operative societies, social welfare, village planning or any other matter to which the executive power of the State extends.\n" +
                "7. District and Regional Funds.(1) There shall be constituted for each autonomous district, a District Fund and for each autonomous region, a Regional Fund to which shall be credited all moneys received respectively by the District Council for that district and the Regional Council for that region in the course of the administration of such district or region, as the case may be, in accordance with the provisions of this Constitution. \n" +
                "(2) The Governor may make rules for the management of the District Fund, or, as the case may be, the Regional Fund and for the procedure to be followed in respect of payment of money into the said Fund, the withdrawal of moneys therefrom, the custody of moneys therein and any other matter connected with or ancillary to the matters aforesaid. \n" +
                "(3) The accounts of the District Council or, as the case may be, the Regional Council shall be kept in such form as the Comptroller and Auditor-General of India may, with the approval of the President, prescribe. \n" +
                "(4) The Comptroller and Auditor-General shall cause the accounts of the District and Regional Councils to be audited in such manner as he may think fit, and the reports of the Comptroller and Auditor-General relating to such accounts shall be submitted to the Governor who shall cause them to be laid before the Council.\n" +
                "8. Powers to assess and collect land revenue and to impose taxes.\n" +
                "(1) The Regional Council for an autonomous region in respect of all lands within such region and the District Council for an autonomous district in respect of all lands within the district except those which are in the areas under the authority of Regional Councils, if any, within the district, shall have the power to assess and collect revenue in respect of such lands in accordance with the principles for the time being followed by the Government of the State in assessing lands for the purpose of land revenue in the State generally.\n" +
                "(2) The Regional Council for an autonomous region in respect of areas within such region and the District Council for an autonomous district in respect of all areas in the district except those which are under the authority of Regional Councils, if any, within the district, shall have power to levy and collect taxes on lands and buildings, and tolls on persons resident within such areas.\n" +
                "(3) The District Council for an autonomous district shall have the power to levy and collect all or any of the following taxes within such district, that is to say \n" +
                "(a) taxes on professions, trades, callings and employments;\n" +
                "(b) taxes on animals, vehicles and boats;\n" +
                "(c) taxes on the entry of goods into a market for sale therein, and tolls on passengers and goods carried in ferries; and\n" +
                "(d) taxes for the maintenance of schools, dispensaries or roads.\n" +
                "(4) A Regional Council or District Council, as the case may be, may make regulations to provide for the levy and collection of any of the taxes specified in sub-paragraphs (2) and (3) of this paragraph and every such regulation shall be submitted forthwith to the Governor and, until assented to by him, shall have no effect.\n" +
                "9. Licences or leases for the purpose of prospecting for, or extraction of, minerals.(1) Such share of the royalties accruing each year from licences or leases for the purpose of prospecting for, or the extraction of, minerals granted by the Government of the State in respect of any area within an autonomous district as may be agreed upon between the Government of the State and the District Council of such district shall be made over to that District Council.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 9 has been amended in its application to the States of Tripura and Mizoram by the Sixth Schedule to the Constitution (Amendment) Act, 1988 (67 of 1988), s. 2, so as to insert the following sub-paragraph after sub-paragraph (2), namely :-\n" +
                "(3) The Governor may, by order, direct that the share of royalties to be made over to a District Council under this paragraph shall be made over to that Council within a period of one year from the date of any agreement under sub-paragraph (1) or, as the case may be, of any determination under sub-paragraph (2).\n" +
                "-----------------------\n" +
                "(2) If any dispute arises as to the share of such royalties to be made over to a District Council, it shall be referred to the Governor for determination and the amount determined by the Governor in his discretion shall be deemed to be the amount payable under sub-paragraph (1) of this paragraph to the District Council and the decision of the Governor shall be final.\n" +
                "10. Power of District Council to make regulations for the control of money-lending and trading by non-tribals.(1) The District Council of an autonomous district may make regulations for the regulation and control of money-lending or trading within the district by persons other than Scheduled Tribes resident in the district. \n" +
                "(2) In particular and without prejudice to the generality of the foregoing power, such regulations may\n" +
                "(a) prescribe that no one except the holder of a licence issued in that behalf shall carry on the business of money-lending;\n" +
                "(b) prescribe the maximum rate of interest which may be charged or be recovered by a money-lender;\n" +
                "(c) provide for the maintenance of accounts by money-lenders and for the inspection of such accounts by officers appointed in that behalf by the District Council;\n" +
                "(d) prescribe that no person who is not a member of the Scheduled Tribes resident in the district shall carry on wholesale or retail business in any commodity except under a licence issued in that behalf by the District Council :\n" +
                "Provided that no regulations may be made under this paragraph unless they are passed by a majority of not less than three-fourths of the total membership of the District Council:\n" +
                "Provided further that it shall not be competent under any such regulations to refuse the grant of a licence to a money-lender or a trader who has been carrying on business within the district since before the time of the making of such regulations.\n" +
                "(3) All regulations made under this paragraph shall be submitted forthwith to the Governor and, until assented to by him, shall have no effect.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 10 has been amended in its application to the States of Tripura and Mizoram by the Sixth Schedule to the Constitution (Amendment) Act, 1988 (67 of 1988), s.2, as under--\n" +
                "(a) in the heading, the words by non-tribals shall be omitted; \n" +
                "(b) in sub-paragraph (1), the words other than Scheduled Tribes shall be omitted;\n" +
                "(c) in sub-paragraph (2), for clause (d), the following clause shall be substituted, namely: \n" +
                "\"(d) prescribe that no person resident in the district shall carry on any trade, whether wholesale or retail, except under a licence issued in that behalf by the District Council.\n" +
                "note[2] Paragraph 10 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2 , so as to insert the following sub-paragraph after sub-paragraph (3), namely: \n" +
                "(4) Nothing in this paragraph shall apply to the Bodoland Territorial Council constituted under the proviso to sub-paragraph (3) of paragraph 2 of this Schedule.\n" +
                "-----------------------\n" +
                "11. Publication of laws, rules and regulations made under the Schedule.All laws, rules and regulations made under this Schedule by a District Council or a Regional Council shall be published forthwith in the Official Gazette of the State and shall on such publication have the force of law.\n" +
                "12. Application of Acts of Parliament and of the Legislature of the State of Assam to autonomous districts and autonomous regions in the State of Assam. \n" +
                "(1) Notwithstanding anything in this Constitution, \n" +
                "(a) no Act of the Legislature of the State of Assam in respect of any of the matters specified in paragraph 3 of this Schedule as matters with respect to which a District Council or a Regional Council may make laws, and no Act of the Legislature of the State of Assam prohibiting or restricting the consumption of any non-distilled alcoholic liquor shall apply to any autonomous district or autonomous region in that State unless in either case the District Council for such district or having jurisdiction over such region by public notification so directs, and the District Council in giving such direction with respect to any Act may direct that the Act shall in its application to such district or region or any part thereof have effect subject to such exceptions or modifications as it thinks fit;\n" +
                "(b) the Governor may, by public notification, direct that any Act of Parliament or of the Legislature of the State of Assam to which the provisions of clause (a) of this sub-paragraph do not apply shall not apply to an autonomous district or an autonomous region in that State, or shall apply to such district or region or any part thereof subject to such exceptions or modifications as he may specify in the notification.\n" +
                "(2) Any direction given under sub-paragraph (1) of this paragraph may be given so as to have retrospective effect.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 12 has been amended to its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 1995 (42 of 1995), s.2, as under,- \n" +
                "in paragraph 12, in sub-paragraph (1), for the words and figure matters specified in paragraph 3 of this Schedule, the words, figures and letter matters specified in paragraph 3 or paragraph 3A of this Schedule shall be substituted.\n" +
                "note[2] Paragraph 12 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, as under,\n" +
                "in paragraph 12, in sub-paragraph (1), in clause (a), for the words, figures and letter matters specified in paragraph 3 or paragraph 3A of this Schedule, the words, figures and letter matters specified in paragraph 3 or paragraph 3A or paragraph 3B of this Schedule shall be substituted.\n" +
                "-----------------------\n" +
                "12A. Application of Acts of Parliament and of the Legislature of the State of Meghalaya to autonomous districts and autonomous regions in the State of Meghalaya.Notwithstanding anything in this Constitution,\n" +
                "(a) if any provision of a law made by a District or Regional Council in the State of Meghalaya with respect to any matter specified in sub-paragraph (1) of paragraph 3 of this Schedule or if any provision of any regulation made by a District Council or a Regional Council in that State under paragraph 8 or paragraph 10 of this Schedule, is repugnant to any provision of a law made by the Legislature of the State of Meghalaya with respect to that matter, then, the law or regulation made by the District Council or, as the case may be, the Regional Council whether made before or after the law made by the Legislature of the State of Meghalaya, shall, to the extent of repugnancy, be void and the law made by the Legislature of the State of Meghalaya shall prevail; \n" +
                "(b) the President may, with respect to any Act of Parliament, by notification, direct that it shall not apply to an autonomous district or an autonomous region in the State of Meghalaya, or shall apply to such district or region or any part thereof subject to such exceptions or modifications as he may specify in the notification and any such direction may be given so as to have retrospective effect.\n" +
                "12AA. Application of Acts of Parliament and of the Legislature of the State of Tripura to the autonomous districts and autonomous regions in the State of Tripura.Notwithstanding anything in this Constitution,\n" +
                "(a) no Act of the Legislature of the State of Tripura in respect of any of the matters specified in paragraph 3 of this Schedule as matters with respect to which a District Council or a Regional Council may make laws, and no Act of the Legislature of the State of Tripura prohibiting or restricting the consumption of any non-distilled alcoholic liquor shall apply to any autonomous district or autonomous region in that State unless, in either case the, District Council for such district or having jurisdiction over such region by public notification so directs, and the District Council in giving such direction with respect to any Act may direct that the Act shall, in its application to that district or such region or any part thereof have effect subject to such exceptions or modifications as it thinks fit;\n" +
                "(b) the Governor may, by public notification, direct that any Act of the Legislature of the State of Tripura to which the provisions of clause (a) of this sub-paragraph do not apply, shall not apply to the autonomous district or any autonomous region in that State, or shall apply to that district or such region, or any part thereof, subject to such exceptions or modifications, as he may specify in the notification;\n" +
                "(c) the President may, with respect to any Act of Parliament, by notification, direct that it shall not apply to the autonomous district or an autonomous region in the State of Tripura, or shall apply to such district or region or any part thereof, subject to such exceptions or modifications as he may specify in the notification and any such direction may be given so as to have retrospective effect. \n" +
                "12B. Application of Acts of Parliament and of the Legislature of the State of Mizoram to autonomous districts and autonomous regions in the State of Mizoram.Notwithstanding anything in this Constitution,  \n" +
                "(a) no Act of the Legislature of the State of Mizoram in respect of any of the matters specified in paragraph 3 of this Schedule as matters with respect to which a District Council or a Regional Council may make laws, and no Act of the Legislature of the State of Mizoram prohibiting or restricting the consumption of any non-distilled alcoholic liquor shall apply to any autonomous district or autonomous region in that State unless, in either case, the District Council for such district or having jurisdiction over such region, by public notification, so directs, and the District Council, in giving such direction with respect to any Act, may direct that the Act shall, in its application to such district or region or any part thereof, have effect subject to such exceptions or modifications as it thinks fit;\n" +
                "(b) the Governor may, by public notification, direct that any Act of the Legislature of the State of Mizoram to which the provisions of clause (a) of this sub-paragraph do not apply, shall not apply to an autonomous district or an autonomous region in that State, or shall apply to such district or region, or any part thereof, subject to such exceptions or modifications, as he may specify in the notification; \n" +
                "(c) the President may, with respect to any Act of Parliament, by notification, direct that it shall not apply to an autonomous district or an autonomous region in the State of Mizoram, or shall apply to such district or region or any part thereof, subject to such exceptions or modifications as he may specify in the notification and any such direction may be given so as to have retrospective effect.\n" +
                "13. Estimated receipts and expenditure pertaining to autonomous districts to be shown separately in the annual financial statement.The estimated receipts and expenditure pertaining to an autonomous district which are to be credited to, or is to be made from, the Consolidated Fund of the State shall be first placed before the District Council for discussion and then after such discussion be shown separately in the annual financial statement of the State to be laid before the Legislature of the State under article 202.\n" +
                "14. Appointment of Commission to inquire into and report on the administration of autonomous districts and autonomous regions.(1) The Governor may at any time appoint a Commission to examine and report on any matter specified by him relating to the administration of the autonomous districts and autonomous regions in the State, including matters specified in clauses (c), (d), (e) and (f) of sub-paragraph (3) of paragraph 1 of this Schedule, or may appoint a Commission to inquire into and report from time to time on the administration of autonomous districts and autonomous regions in the State generally and in particular on \n" +
                "(a) the provision of educational and medical facilities and communications in such districts and regions;\n" +
                "(b) the need for any new or special legislation in respect of such districts and regions; and\n" +
                "(c) the administration of the laws, rules and regulations made by the District and Regional Councils;\n" +
                "and define the procedure to be followed by such Commission.\n" +
                "(2) The report of every such Commission with the recommendations of the Governor with respect thereto shall be laid before the Legislature of the State by the Minister concerned together with an explanatory memorandum regarding the action proposed to be taken thereon by the Government of the State.\n" +
                "(3) In allocating the business of the Government of the State among his Ministers the Governor may place one of his Ministers specially in charge of the welfare of the autonomous districts and autonomous regions in the State.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 14 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 1995 (42 of 1995) , s. 2, as under,--\n" +
                "in paragraph 14, in sub-paragraph (2), the words with the recommendations of the Governor with respect thereto shall be omitted.\n" +
                "-----------------------\n" +
                "15. Annulment or suspension of acts and resolutions of District and Regional Councils.(1) If at any time the Governor is satisfied that an act or resolution of a District or a Regional Council is likely to endanger the safety of India or is likely to be prejudicial to public order, he may annul or suspend such act or resolution and take such steps as he may consider necessary (including the suspension of the Council and the assumption to himself of all or any of the powers vested in or exercisable by the Council) to prevent the commission or continuance of such act, or the giving of effect to such resolution.\n" +
                "(2) Any order made by the Governor under sub-paragraph (1) of this paragraph together with the reasons therefor shall be laid before the Legislature of the State as soon as possible and the order shall, unless revoked by the Legislature of the State, continue in force for a period of twelve months from the date on which it was so made:\n" +
                "Provided that if and so often as a resolution approving the continuance in force of such order is passed by the Legislature of the State, the order shall unless cancelled by the Governor continue in force for a further period of twelve months from the date on which under this paragraph it would otherwise have ceased to operate.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 15 has been amended in its application to the States of Tripura and Mizoram by the Sixth Schedule to the Constitution (Amendment) Act, 1988 (67 of 1988), s. 2, as under,--\n" +
                "(a) in the opening paragraph, for the words by the Legislature of the State, the words by him shall be substituted;\n" +
                "(b) the proviso shall be omitted.\n" +
                "-----------------------\n" +
                "16. Dissolution of a District or a Regional Council. (1) The Governor may on the recommendation of a Commission appointed under paragraph 14 of this Schedule by public notification order the dissolution of a District or a Regional Council, and \n" +
                "(a) direct that a fresh general election shall be held immediately for the reconstitution of the Council, or\n" +
                "(b) subject to the previous approval of the Legislature of the State assume the administration of the area under the authority of such Council himself or place the administration of such area under the Commission appointed under the said paragraph or any other body considered suitable by him for a period not exceeding twelve months: \n" +
                "Provided that when an order under clause (a) of this paragraph has been made, the Governor may take the action referred to in clause (b) of this paragraph with regard to the administration of the area in question pending the reconstitution of the Council on fresh general election:\n" +
                "Provided further that no action shall be taken under clause (b) of this paragraph without giving the District or the Regional Council, as the case may be, an opportunity of placing its views before the Legislature of the State.\n" +
                "(2) If at any time the Governor is satisfied that a situation has arisen in which the administration of an autonomous district or region cannot be carried on in accordance with the provisions of this Schedule, he may, by public notification, assume to himself all or any of the functions or powers vested in or exercisable by the District Council or, as the case may be, the Regional Council and declare that such functions or powers shall be exercisable by such person or authority as he may specify in this behalf, for a period not exceeding six months:\n" +
                "Provided that the Governor may by a further order or orders extend the operation of the initial order by a period not exceeding six months on each occasion.\n" +
                "(3) Every order made under sub-paragraph (2) of this paragraph with the reasons therefor shall be laid before the Legislature of the State and shall cease to operate at the expiration of thirty days from the date on which the State Legislature first sits after the issue of the order, unless, before the expiry of that period it has been approved by that State Legislature.\n" +
                "-----------------------\n" +
                "note[1]. Paragraph 16 has been amended in its application to the States of Tripura and Mizoram by the Sixth Schedule to the Constitution (Amendment) Act, 1988 (67 of 1988) s. 2, as under,-- \n" +
                "(a) in sub-paragraph (1), the words subject to the previous approval of the Legislature of the State occurring in clause (b), and the second proviso shall be omitted; \n" +
                "(b) for sub-paragraph (3), the following sub-paragraph shall be substituted, namely:--\n" +
                "(3) Every order made under sub-paragraph (1) or sub-paragraph (2) of this paragraph, along with the reasons therefor shall be laid before the Legislature of the State..\n" +
                "-----------------------\n" +
                "17. Exclusion of areas from autonomous districts in forming constituencies in such districts.For the purposes of elections to the egislative Assembly of Assam or Meghalaya or Tripura or Mizoram, the Governor may by order declare that any area within an autonomous district in the State of Assam or Meghalaya or Tripura or Mizoram, as the case may be, shall not form part of any constituency to fill a seat or seats in the Assembly reserved for any such district but shall form part of a constituency to fill a seat or seats in the Assembly not so reserved to be specified in the order.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 17 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2 , so as to insert the following proviso, namely: \n" +
                "Provided that nothing in this paragraph shall apply to the Bodoland Territorial Areas District.\n" +
                "-----------------------\n" +
                "19. Transitional provisions.(1) As soon as possible after the commencement of this Constitution the Governor shall take steps for the constitution of a District Council for each autonomous district in the State under this Schedule and, until a District Council is so constituted for an autonomous district, the administration of such district shall be vested in the Governor and the following provisions shall apply to the administration of the areas within such district instead of the foregoing provisions of this Schedule, namely:\n" +
                "(a) no Act of Parliament or of the Legislature of the State shall apply to any such area unless the Governor by public notification so directs; and the Governor in giving such a direction with respect to any Act may direct that the Act shall, in its application to the area or to any specified part thereof, have effect subject to such exceptions or modifications as he thinks fit;\n" +
                "(b) the Governor may make regulations for the peace and good government of any such area and any regulations so made may repeal or amend any Act of Parliament or of the Legislature of the State or any existing law which is for the time being applicable to such area. \n" +
                "(2) Any direction given by the Governor under clause (a) of sub-paragraph (1) of this paragraph may be given so as to have retrospective effect.\n" +
                "(3) All regulations made under clause (b) of sub-paragraph (1) of this paragraph shall be submitted forthwith to the President and, until assented to by him, shall have no effect.\n" +
                "-----------------------\n" +
                "note[1] Paragraph 19 has been amended in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 2003 (44 of 2003), s. 2, so as to insert the following sub-paragraph after sub-paragraph (3), namely :\n" +
                "(4) As soon as possible after the commencement of this Act, and Interim Executive Council for Bodoland Territorial Areas District in Assam shall be formed by the Governor from amongst leaders of the Bodo movement, including the signatories to the Memorandum of Settlement, and shall provide adequate representation to the non-tribal communities in that area: \n" +
                "Provided that Interim Council shall be for a period of six months during which endeavour to hold the election to the Council shall be made. \n" +
                "Explanation.-- For the purposes of this sub-paragraph, the expression Memorandum of Settlement means the Memorandum signed on the 10th day of February, 2003 between Government of India, Government of Assam and Bodo Liberation Tigers.\n" +
                "-----------------------\n" +
                "20. Tribal areas.(1) The areas specified in Parts I, II, IIA and III of the table below shall respectively be the tribal areas within the State of Assam, the State of Meghalaya, the State of Tripura and the State of Mizoram.\n" +
                "(2) Any reference in Part I, Part II or Part III of the table below to any district shall be construed as a reference to the territories comprised within the autonomous district of that name existing immediately before the day appointed under clause (b) of section 2 of the North-Eastern Areas (Reorganisation) Act, 1971:\n" +
                "Provided that for the purposes of clauses (e) and (f) of sub-paragraph (1) of paragraph 3, paragraph 4, paragraph 5, paragraph 6, sub -paragraph (2), clauses (a), (b) and (d) of sub-paragraph (3) and sub-paragraph (4) of paragraph 8 and clause (d) of sub-paragraph (2) of paragraph 10 of this Schedule, no part of the area comprised within the municipality of Shillong shall be deemed to be within the Khasi Hills District.\n" +
                "(3) The reference in Part IIA in the table below to the \"Tripura Tribal Areas District\" shall be construed as a reference to the territory comprising the tribal areas specified in the First Schedule to the Tripura Tribal Areas Autonomous District Council Act, 1979.\n" +
                "PART I\n" +
                "1. The North Cachar Hills District.\n" +
                "2. The Karbi Anglong District.\n" +
                "3. The Bodoland Territorial Area District.\n" +
                "PART II\n" +
                "1. Khasi Hills District.\n" +
                "2. Jaintia Hills District.\n" +
                "3. The Garo Hills District.\n" +
                "PART IIA\n" +
                "Tripura Tribal Areas District\n" +
                "Part III\n" +
                "1. The Chakma District.\n" +
                "2. The Mara District.\n" +
                "3. The Lai District.\n" +
                "20A. Dissolution of the Mizo District Council.(1) Notwithstanding anything in this Schedule, the District Council of the Mizo District existing immediately before the prescribed date (hereinafter referred to as the Mizo District Council) shall stand dissolved and cease to exist.\n" +
                "(2) The Administrator of the Union territory of Mizoram may, by one or more orders, provide for all or any of the following matters, namely:\n" +
                "(a) the transfer, in whole or in part, of the assets, rights and liabilities of the Mizo District Council (including the rights and liabilities under any contract made by it) to the Union or to any other authority;\n" +
                "(b) the substitution of the Union or any other authority for the Mizo District Council, or the addition of the Union or any other authority, as a party to any legal proceedings to which the Mizo District Council is a party;\n" +
                "(c) the transfer or re-employment of any employees of the Mizo District Council to or by the Union or any other authority, the terms and conditions of service applicable to such employees after such transfer or re-employment;\n" +
                "(d) the continuance of any laws, made by the Mizo District Council and in force immediately before its dissolution, subject to such adaptations and modifications, whether by way of repeal or amendment, as the Administrator may make in this behalf, until such laws are altered, repealed or amended by a competent Legislature or other competent authority;\n" +
                "(e) such incidental, consequential and supplementary matters as the Administrator considers necessary. \n" +
                "Explanation.In this paragraph and in paragraph 20B of this Schedule, the expression \"prescribed date\" means the date on which the Legislative Assembly of the Union territory of Mizoram is duly constituted under and in accordance with the provisions of the Government of Union Territories Act, 1963.\n" +
                "20B. Autonomous regions in the Union territory of Mizoram to be autonomous districts and transitory provisions consequent thereto.(1) Notwithstanding anything in this Schedule, \n" +
                "(a) every autonomous region existing immediately before the prescribed date in the Union territory of Mizoram shall, on and from that date, be an autonomous district in that Union territory (hereafter referred to as the corresponding new district) and the Administrator thereof may, by one or more orders, direct that such consequential amendments as are necessary to give effect to the provisions of this clause shall be made in paragraph 20 of this Schedule (including Part III of the table appended to that paragraph) and thereupon the said paragraph and the said Part III shall be deemed to have been amended accordingly;\n" +
                "(b) every Regional Council of an autonomous region in the Union territory of Mizoram existing immediately before the prescribed date (hereafter referred to as the existing Regional Council) shall, on and from that date and until a District Council is duly constituted for the corresponding new district, be deemed to be the District Council of that district (hereafter referred to as the corresponding new District Council).\n" +
                "(2) Every member whether elected or nominated of an existing Regional Council shall be deemed to have been elected or, as the case may be, nominated to the corresponding new District Council and shall hold office until a District Council is duly constituted for the corresponding new district under this Schedule. \n" +
                "(3) Until rules are made under sub-paragraph (7) of paragraph 2 and sub-paragraph (4) of paragraph 4 of this Schedule by the corresponding new District Council, the rules made under the said provisions by the existing Regional Council and in force immediately before the prescribed date shall have effect in relation to the corresponding new District Council subject to such adaptations and modifications as may be made therein by the Administrator of the Union territory of Mizoram.\n" +
                "(4) The Administrator of the Union territory of Mizoram may, by one or more orders, provide for all or any of the following matters, namely:\n" +
                "(a) the transfer in whole or in part of the assets, rights and liabilities of the existing Regional Council (including the rights and liabilities under any contract made by it) to the corresponding new District Council;\n" +
                "(b) the substitution of the corresponding new District Council for the existing Regional Council as a party to the legal proceedings to which the existing Regional Council is a party;\n" +
                "(c) the transfer or re-employment of any employees of the existing Regional Council to or by the corresponding new District Council, the terms and conditions of service applicable to such employees after such transfer or re-employment;\n" +
                "(d) the continuance of any laws made by the existing Regional Council and in force immediately before the prescribed date, subject to such adaptations and modifications, whether by way of repeal or amendment, as the Administrator may make in this behalf until such laws are altered, repealed or amended by a competent Legislature or other competent authority;\n" +
                "(e) such incidental, consequential and supplementary matters as the Administrator considers necessary.\n" +
                "-----------------------\n" +
                "note[1] After paragraph 20B, the following paragraph has been inserted in its application to the State of Assam by the Sixth Schedule to the Constitution (Amendment) Act, 1995 (42 of 1995), s. 2, namely:\n" +
                "20BA. Exercise of discretionary powers by the Governor in the discharge of his functions.  The Governor in the discharge of his functions under sub-paragraphs (2) and (3) of paragraph 1, sub-paragraphs (1), (6), sub-paragraph (6A) excluding the first proviso and sub-paragraph (7) of paragraph 2, sub-paragraph (3) of paragraph 3, sub-paragraph (4) of paragraph 4, paragraph 5, sub-paragraph (1) of paragraph 6, sub-paragraph (2) of paragraph 7, sub-paragraph (4) of paragraph 8, sub-paragraph (3) of paragraph 9, sub-paragraph (3) of paragraph 10, sub-paragraph (1) of paragraph 14, sub-paragraph (1) of paragraph 15 and sub-paragraphs (1) and (2) of paragraph 16 of this Schedule, shall, after consulting the Council of Ministers and the North Cachar Hills Autonomous Council or the Karbi Anglong Autonomous Council, as the case may be, take such action as he considers necessary in his discretion. . \n" +
                "note[2] After paragraph 20B, the following paragraph has been inserted in its application to the States of Tripura and Mizoram, by the Sixth Schedule to the Constitution (Amendment) Act, 1988 (67 of 1988), s. 2, namely: \n" +
                "20BB. Exercise of discretionary powers by the Governor in the discharge of his functions.-The Governor, in the discharge of his functions under sub-paragraphs (2) and (3) of paragraph 1, sub-paragraphs (1) and (7) of paragraph 2, sub-paragraph (3) of paragraph 3, sub-paragraph (4) of paragraph 4, paragraph 5, sub-paragraph (1) of paragraph 6, sub-paragraph (2) of paragraph 7, sub-paragraph (3) of paragraph 9, sub-paragraph (1) of paragraph 14, sub-paragraph (1) of paragraph 15 and sub-paragraphs (1) and (2) of paragraph 16 of this Schedule, shall, after consulting the Council of Ministers, and if he thinks it necessary, the District Council or the Regional Council concerned, take such action as he considers necessary in his discretion.\n" +
                "-----------------------\n" +
                "20C. Interpretation.Subject to any provision made in this behalf, the provisions of this Schedule shall, in their application to the Union territory of Mizoram, have effect\n" +
                "(1) as if references to the Governor and Government of the State were references to the Administrator of the Union territory appointed under article 239, references to State (except in the expression \"Government of the State\") were references to the Union territory of Mizoram and references to the State Legislature were references to the Legislative Assembly of the Union territory of Mizoram;\n" +
                "(2) as if\n" +
                "(a) in sub-paragraph (5) of paragraph 4, the provision for consultation with the Government of the State concerned had been omitted;\n" +
                "(b) in sub-paragraph (2) of paragraph 6, for the words \"to which the executive power of the State extends\", the words \"with respect to which the Legislative Assembly of the Union territory of Mizoram has power to make laws\" had been substituted;\n" +
                "(c) in paragraph 13, the words and figures \"under article 202\" had been omitted.\n" +
                "21. Amendment of the Schedule.(1) Parliament may from time to time by law amend by way of addition, variation or repeal any of the provisions of this Schedule and, when the Schedule is so amended, any reference to this Schedule in this Constitution shall be construed as a reference to such Schedule as so amended.\n" +
                "(2) No such law as is mentioned in sub-paragraph (1) of this paragraph shall be deemed to be an amendment of this Constitution for the purposes of article 368.");
    }
}
